create table DOCTOR
(
    ID             BIGINT generated by default as identity (start with 1)
            primary key,
    NAME           VARCHAR(50) not null,
    SURNAME        VARCHAR(50) not null,
    PATRONYMIC     VARCHAR(50) not null,
    SPECIALIZATION VARCHAR(50) not null
);

create table PATIENT
(
    ID           BIGINT generated by default as identity (start with 1)
        primary key,
    NAME         VARCHAR(50) not null,
    SURNAME      VARCHAR(50) not null,
    PATRONYMIC   VARCHAR(50) not null,
    PHONE_NUMBER BIGINT      not null
);

create table RECIPE
(
    ID          BIGINT generated by default as identity (start with 1)
            primary key,
    DATE_CREATE Date    not null,
    VALIDITY    Date    not null,
    PRIORITY    VARCHAR(10)  not null,
    DESCRIPTION VARCHAR(50) not null,
    ID_PATIENT  BIGINT      not null
        constraint RECIPE_PATIENT_ID_FK
            references PATIENT
            on update cascade,
    ID_DOCTOR   BIGINT      not null
        constraint RECIPE_DOCTOR_ID_FK
            references DOCTOR
            on update cascade
);
